agentSandboxController:
  agentSandboxController:
    args:
    - --leader-elect=true
    - --extensions
    image:
      repository: registry.k8s.io/agent-sandbox/agent-sandbox-controller
      tag: v0.3.10
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
