apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-controller
  labels:
  {{- include "agent-sandbox.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "agent-sandbox.fullname" . }}-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "agent-sandbox.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-controller
  labels:
  {{- include "agent-sandbox.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - agent-sandbox-webhook-certs
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-controller
  labels:
  {{- include "agent-sandbox.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "agent-sandbox.fullname" . }}-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "agent-sandbox.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-controller
  labels:
  {{- include "agent-sandbox.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/finalizers
  - sandboxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - sandboxclaims.extensions.agents.x-k8s.io
  - sandboxes.agents.x-k8s.io
  - sandboxtemplates.extensions.agents.x-k8s.io
  - sandboxwarmpools.extensions.agents.x-k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
