apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-agent-sandbox-controller
  labels:
    app: agent-sandbox-controller
  {{- include "agent-sandbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agentSandboxController.replicas }}
  selector:
    matchLabels:
      app: agent-sandbox-controller
    {{- include "agent-sandbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
      {{- include "agent-sandbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.agentSandboxController.agentSandboxController.args | nindent
          8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.agentSandboxController.agentSandboxController.image.repository
          }}:{{ .Values.agentSandboxController.agentSandboxController.image.tag | default
          .Chart.AppVersion }}'
        name: agent-sandbox-controller
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: healthz
          protocol: TCP
        resources: {}
      nodeSelector: {{- toYaml .Values.agentSandboxController.nodeSelector | nindent 8
        }}
      serviceAccountName: {{ include "agent-sandbox.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.agentSandboxController.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.agentSandboxController.topologySpreadConstraints
        | nindent 8 }}
