apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-sandbox.fullname" . }}-controller
  labels:
    app: agent-sandbox-controller
  {{- include "agent-sandbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: agent-sandbox-controller
    {{- include "agent-sandbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
      {{- include "agent-sandbox.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.controller.agentSandboxController.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controller.agentSandboxController.image.repository }}:{{ .Values.controller.agentSandboxController.image.tag
          | default .Chart.AppVersion }}
        name: agent-sandbox-controller
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: healthz
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources: {}
      nodeSelector: {{- toYaml .Values.controller.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "agent-sandbox.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.controller.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.controller.topologySpreadConstraints
        | nindent 8 }}
